1. Introduction to Pandas

Pandas is a Python library for tabular data (rows + columns), similar to Excel or SQL tables but much more powerful.[youtube +1]

In [2]:
import pandas as pd

Main objects:

•	 Series : 1D labeled array (like a single column).

•	 DataFrame : 2D labeled table (like an entire sheet).

2. Creating Pandas Series

In [3]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s

a    10
b    20
c    30
dtype: int64

•	Values:  [10, 20, 30] 
•	Index:  ['a', 'b', 'c'] 

You can also create from a dict:

In [4]:
s2 = pd.Series({'x': 1, 'y': 2, 'z': 3})
s2

x    1
y    2
z    3
dtype: int64

Series of temperatures for 7 days with day names as index

In [7]:
temps = pd.Series(
    [32, 34, 39, 41, 33, 40, 38],
    index=['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
)
temps

Monday       32
Tuesday      34
Wednesday    39
Thursday     41
Friday       33
Saturday     40
Sunday       38
dtype: int64

3. Creating DataFrames From dictionaries

In [8]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 28],
    'city': ['Ahilyanagar', 'Pune', 'Mumbai']
}
df = pd.DataFrame(data)
df

      name  age         city
0    Alice   25  Ahilyanagar
1      Bob   30         Pune
2  Charlie   28       Mumbai

From list of lists / list of dicts

In [10]:
# List of lists
rows = [
    ['Alice', 25, 'Ahilyanagar'],
    ['Bob', 30, 'Pune'],
    ['Charlie', 28, 'Mumbai']
]
df2 = pd.DataFrame(rows, columns=['name', 'age', 'city'])

# List of dicts
rows2 = [
    {'name': 'Alice', 'age': 25, 'city': 'Ahilyanagar'},
    {'name': 'Bob', 'age': 30, 'city': 'Pune'},
]
df3 = pd.DataFrame(rows2)
df3

    name  age         city
0  Alice   25  Ahilyanagar
1    Bob   30         Pune

From Series

In [11]:
s_name = pd.Series(['Alice', 'Bob'], name='name')
s_age = pd.Series([25, 30], name='age')
df4 = pd.DataFrame({'name': s_name, 'age': s_age})
df4

    name  age
0  Alice   25
1    Bob   30

DataFrame of students with columns  name ,  math_score ,  science_score  using a dict.

In [16]:
students = {
    'name': ['Dave', 'Eve', 'Frank'],
    'math_score': [88, 92, 75],
    'science_score': [90, 85, 80]
}
df_students = pd.DataFrame(students)
print(df_students)

    name  math_score  science_score
0   Dave          88             90
1    Eve          92             85
2  Frank          75             80

4. Pandas DataFrames from CSV, Excel, JSON, Databases From CSV

In [4]:
df_csv = pd.read_csv('data.csv')
df_csv

    name  age         city
0  Alice   25  Ahilyanagar
1    Bob   30         Pune

Common options:

•	 sep  for delimiter

•	 header  to specify header row

•	 na_values  for missing value markers From Excel

For nested JSON, you may need  pd.json_normalize From Databases

In [8]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/envs/trading_development/lib/python3.12/site-packages (from sqlalchemy) (4.14.0)
Downloading sqlalchemy-2.0.51-cp312-cp312-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 3.7 MB/s eta 0:00:00a 0:00:01
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [11]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS employees (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        age INTEGER,
        department TEXT
    );
    """))
    
    conn.execute(text("DELETE FROM employees"))
    conn.execute(
        text("INSERT INTO employees (name, age, department) VALUES (:name, :age, :dept)"),
        [
            {"name": "Alice", "age": 25, "dept": "HR"},
            {"name": "Bob", "age": 30, "dept": "Sales"},
            {"name": "Charlie", "age": 28, "dept": "Engineering"},
        ],
    )
conn.close()

In [12]:
df_db = pd.read_sql('SELECT * FROM employees', engine)
df_db

   id     name  age   department
0   4    Alice   25           HR
1   5      Bob   30        Sales
2   6  Charlie   28  Engineering

In [ ]:
// Exercise:
// •	Create a small CSV file  students.csv  and read it.
// •	Create a small JSON file  students.json  and read it.

5. Extracting Rows Using  loc  and  iloc 
Key difference:

•	 loc : label-based (use index/column names).

•	 iloc : position-based (use 0-based integer indices).

In [13]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 28],
}, index=['r1', 'r2', 'r3'])
df

       name  age
r1    Alice   25
r2      Bob   30
r3  Charlie   28

Using  loc  (labels)

In [18]:
# Single row by label
df.loc['r2']

# Multiple rows
df.loc[['r1', 'r3']]

# Row and column by label
df.loc['r2', 'age']

# Slice (end inclusive)
df.loc['r1':'r3', 'name':'age']  # includes 'r3' and 'age'

       name  age
r1    Alice   25
r2      Bob   30
r3  Charlie   28

Using  iloc  (positions)

In [19]:
# Single row by position
df.iloc[1]  # second row

# Multiple rows
df.iloc[[0, 2]]

# Row and column by position
df.iloc[1, 1]  # second row, second column

# Slice (end exclusive)
df.iloc[0:2, 0:2]  # rows 0,1; cols 0,1 (end not included)

     name  age
r1  Alice   25
r2    Bob   30

In [ ]:
// Exercise: Given a DataFrame with index as dates, select:
// •	Rows from 2025-01-01 to 2025-01-10 using  loc .
// •	First 5 rows and first 3 columns using  iloc .

6. Pandas Dealing with Rows and Columns

Selecting columns

In [20]:
df['name']          # Series
df[['name', 'age']] # DataFrame

       name  age
r1    Alice   25
r2      Bob   30
r3  Charlie   28

Adding / modifying columns

In [22]:
df['grade'] = ['A', 'B', 'C']
df['age_plus_1'] = df['age'] + 1
df

       name  age grade  age_plus_1
r1    Alice   25     A          26
r2      Bob   30     B          31
r3  Charlie   28     C          29

Deleting columns / rows

In [23]:
df.drop('grade', axis=1)         # column
df.drop('r2', axis=0)            # row
df.drop(columns=['grade'])       # alternate
df.drop(index=['r2'])            # alternate
df

       name  age grade  age_plus_1
r1    Alice   25     A          26
r2      Bob   30     B          31
r3  Charlie   28     C          29

Renaming

In [24]:
df.rename(columns={'name': 'student_name'},
          index={'r1': 'row1'})
df

       name  age grade  age_plus_1
r1    Alice   25     A          26
r2      Bob   30     B          31
r3  Charlie   28     C          29

In [ ]:
// Exercise: Add a column  total_score = math_score + science_score  and drop  science_score .

7. Pandas Indexing and Slicing

Beyond  loc / iloc , you can use:

In [27]:
df_csv

    name  age         city
0  Alice   25  Ahilyanagar
1    Bob   30         Pune

In [33]:
# Boolean indexing
df = df_csv
df[df['age'] > 25]

# Using query
filtered_df = df.query('age > 25 and city == "Pune"')
filtered_df

  name  age  city
1  Bob   30  Pune

In [ ]:
// Exercise: Filter students with  math_score >= 80  and  science_score >= 70 .

8. Pandas Data Functionality

Common operations:

In [34]:
df.head()        # first 5 rows
df.tail()        # last 5 rows
df.info()        # types, non-null counts
df.describe()    # numeric summary
df['age'].mean()
df['age'].std()
df.isna().sum()  # missing values per column
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   age     2 non-null      int64
 2   city    2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

    name  age         city
0  Alice   25  Ahilyanagar
1    Bob   30         Pune

Handle missing values:

In [35]:
df.dropna()
df.fillna(0)
df['age'].fillna(df['age'].mean())

0    25
1    30
Name: age, dtype: int64

In [ ]:
// Exercise: Compute average age per city.

9. Pandas Timedelta

Timedelta  represents durations (days, hours, etc.).

In [36]:
td = pd.Timedelta(days=2, hours=3)
td

Timedelta('2 days 03:00:00')

Use in DataFrames:

In [37]:
df = pd.DataFrame({
    'start': pd.to_datetime(['2025-01-01', '2025-01-05']),
    'duration': pd.to_timedelta(['1 day', '2 days'])
})
df['end'] = df['start'] + df['duration']

In [ ]:
// Exercise: Create a DataFrame with  order_date  and  delivery_days  (as Timedelta), then compute  delivery_date .

10. Creating DataFrames from Timedelta

You typically don’t create a DataFrame “from Timedelta” alone; you create a DataFrame that contains Timedelta columns as above.
Example:

In [39]:
df_td = pd.DataFrame({
    'task': ['A', 'B'],
    'duration': pd.to_timedelta(['1h 30m', '45m'])
})
df_td

  task        duration
0    A 0 days 01:30:00
1    B 0 days 00:45:00