In [1]:
import json
import pandas as pd
with open('data.json') as f:
    data = json.load(f)

# Normalizes nested JSON into a flat table
df = pd.json_normalize(data)

In [2]:
df

,id,name,data.color,data.capacity,data,data.capacity GB,data.price,data.generation,data.year,data.CPU model,data.Hard disk size,data.Strap Colour,data.Case Size,data.Color,data.Description,data.Capacity,data.Screen size,data.Generation,data.Price
0,1,Google Pixel 6 Pro,Cloudy White,128 GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,"Apple iPhone 12 Mini, 256GB, Blue",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Apple iPhone 12 Pro Max,Cloudy White,NaN,NaN,512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,"Apple iPhone 11, 64GB",Purple,NaN,NaN,NaN,389.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Samsung Galaxy Z Fold2,Brown,NaN,NaN,NaN,689.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Apple AirPods,NaN,NaN,NaN,NaN,120.00,3rd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Apple MacBook Pro 16,NaN,NaN,NaN,NaN,1849.99,NaN,2019.0,Intel Core i9,1 TB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,Apple Watch Series 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Elderberry,41mm,NaN,NaN,NaN,NaN,NaN,NaN
8,9,Beats Studio3 Wireless,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Red,High-performance wireless noise cancelling hea...,NaN,NaN,NaN,NaN
9,10,Apple iPad Mini 5th Gen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64 GB,7.9,NaN,NaN
10,11,Apple iPad Mini 5th Gen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,254 GB,7.9,NaN,NaN
11,12,Apple iPad Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64 GB,NaN,4th,419.99
12,13,Apple iPad Air,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,256 GB,NaN,4th,519.99

In [4]:
df.columns = df.columns.str.lower()

Apply Data Cleaning Technique (Normalize and Merge)

In [ ]:
df_cleaned = df.groupby(df.columns, axis=1).first()

print("Original DataFrame:\n", df)
print("\nCleaned DataFrame:\n", df_cleaned)

Original DataFrame:
     id                               name    data.color data.capacity  data  \
0    1                 Google Pixel 6 Pro  Cloudy White        128 GB   NaN
1    2  Apple iPhone 12 Mini, 256GB, Blue           NaN           NaN   NaN
2    3            Apple iPhone 12 Pro Max  Cloudy White           NaN   NaN
3    4              Apple iPhone 11, 64GB        Purple           NaN   NaN
4    5             Samsung Galaxy Z Fold2         Brown           NaN   NaN
5    6                      Apple AirPods           NaN           NaN   NaN
6    7               Apple MacBook Pro 16           NaN           NaN   NaN
7    8               Apple Watch Series 8           NaN           NaN   NaN
8    9             Beats Studio3 Wireless           NaN           NaN   NaN
9   10            Apple iPad Mini 5th Gen           NaN           NaN   NaN
10  11            Apple iPad Mini 5th Gen           NaN           NaN   NaN
11  12                     Apple iPad Air           NaN           NaN   NaN
12  13                     Apple iPad Air           NaN           NaN   NaN

    data.capacity gb data.price data.generation  data.year data.cpu model  \
0                NaN        NaN             NaN        NaN            NaN
1                NaN        NaN             NaN        NaN            NaN
2              512.0        NaN             NaN        NaN            NaN
3                NaN     389.99             NaN        NaN            NaN
4                NaN     689.99             NaN        NaN            NaN
5                NaN     120.00             3rd        NaN            NaN
6                NaN    1849.99             NaN     2019.0  Intel Core i9
7                NaN        NaN             NaN        NaN            NaN
8                NaN        NaN             NaN        NaN            NaN
9                NaN        NaN             NaN        NaN            NaN
10               NaN        NaN             NaN        NaN            NaN
11               NaN        NaN             NaN        NaN            NaN
12               NaN        NaN             NaN        NaN            NaN

   data.hard disk size data.strap colour data.case size data.color  \
0                  NaN               NaN            NaN        NaN
1                  NaN               NaN            NaN        NaN
2                  NaN               NaN            NaN        NaN
3                  NaN               NaN            NaN        NaN
4                  NaN               NaN            NaN        NaN
5                  NaN               NaN            NaN        NaN
6                 1 TB               NaN            NaN        NaN
7                  NaN        Elderberry           41mm        NaN
8                  NaN               NaN            NaN        Red
9                  NaN               NaN            NaN        NaN
10                 NaN               NaN            NaN        NaN
11                 NaN               NaN            NaN        NaN
12                 NaN               NaN            NaN        NaN

                                     data.description data.capacity  \
0                                                 NaN           NaN
1                                                 NaN           NaN
2                                                 NaN           NaN
3                                                 NaN           NaN
4                                                 NaN           NaN
5                                                 NaN           NaN
6                                                 NaN           NaN
7                                                 NaN           NaN
8   High-performance wireless noise cancelling hea...           NaN
9                                                 NaN         64 GB
10                                                NaN        254 GB
11                                                NaN         64 GB
12                                                NaN        256 GB

    data.screen size data.generation data.price
0                NaN             NaN        NaN
1                NaN             NaN        NaN
2                NaN             NaN        NaN
3                NaN             NaN        NaN
4                NaN             NaN        NaN
5                NaN             NaN        NaN
6                NaN             NaN        NaN
7                NaN             NaN        NaN
8                NaN             NaN        NaN
9                7.9             NaN        NaN
10               7.9             NaN        NaN
11               NaN             4th     419.99
12               NaN             4th     519.99

Cleaned DataFrame:
     data data.capacity  data.capacity gb data.case size    data.color  \
0   None        128 GB               NaN           None  Cloudy White
1   None          None               NaN           None          None
2   None          None             512.0           None  Cloudy White
3   None          None               NaN           None        Purple
4   None          None               NaN           None         Brown
5   None          None               NaN           None          None
6   None          None               NaN           None          None
7   None          None               NaN           41mm          None
8   None          None               NaN           None           Red
9   None         64 GB               NaN           None          None
10  None        254 GB               NaN           None          None
11  None         64 GB               NaN           None          None
12  None        256 GB               NaN           None          None

   data.cpu model                                   data.description  \
0            None                                               None
1            None                                               None
2            None                                               None
3            None                                               None
4            None                                               None
5            None                                               None
6   Intel Core i9                                               None
7            None                                               None
8            None  High-performance wireless noise cancelling hea...
9            None                                               None
10           None                                               None
11           None                                               None
12           None                                               None

   data.generation data.hard disk size data.price  data.screen size  \
0             None                None       None               NaN
1             None                None       None               NaN
2             None                None       None               NaN
3             None                None     389.99               NaN
4             None                None     689.99               NaN
5              3rd                None      120.0               NaN
6             None                1 TB    1849.99               NaN
7             None                None       None               NaN
8             None                None       None               NaN
9             None                None       None               7.9
10            None                None       None               7.9
11             4th                None     419.99               NaN
12             4th                None     519.99               NaN

   data.strap colour  data.year  id                               name
0               None        NaN   1                 Google Pixel 6 Pro
1               None        NaN   2  Apple iPhone 12 Mini, 256GB, Blue
2               None        NaN   3            Apple iPhone 12 Pro Max
3               None        NaN   4              Apple iPhone 11, 64GB
4               None        NaN   5             Samsung Galaxy Z Fold2
5               None        NaN   6                      Apple AirPods
6               None     2019.0   7               Apple MacBook Pro 16
7         Elderberry        NaN   8               Apple Watch Series 8
8               None        NaN   9             Beats Studio3 Wireless
9               None        NaN  10            Apple iPad Mini 5th Gen
10              None        NaN  11            Apple iPad Mini 5th Gen
11              None        NaN  12                     Apple iPad Air
12              None        NaN  13                     Apple iPad Air

In [6]:
df_cleaned

,data,data.capacity,data.capacity gb,data.case size,data.color,data.cpu model,data.description,data.generation,data.hard disk size,data.price,data.screen size,data.strap colour,data.year,id,name
0,None,128 GB,NaN,None,Cloudy White,None,None,None,None,None,NaN,None,NaN,1,Google Pixel 6 Pro
1,None,None,NaN,None,None,None,None,None,None,None,NaN,None,NaN,2,"Apple iPhone 12 Mini, 256GB, Blue"
2,None,None,512.0,None,Cloudy White,None,None,None,None,None,NaN,None,NaN,3,Apple iPhone 12 Pro Max
3,None,None,NaN,None,Purple,None,None,None,None,389.99,NaN,None,NaN,4,"Apple iPhone 11, 64GB"
4,None,None,NaN,None,Brown,None,None,None,None,689.99,NaN,None,NaN,5,Samsung Galaxy Z Fold2
5,None,None,NaN,None,None,None,None,3rd,None,120.0,NaN,None,NaN,6,Apple AirPods
6,None,None,NaN,None,None,Intel Core i9,None,None,1 TB,1849.99,NaN,None,2019.0,7,Apple MacBook Pro 16
7,None,None,NaN,41mm,None,None,None,None,None,None,NaN,Elderberry,NaN,8,Apple Watch Series 8
8,None,None,NaN,None,Red,None,High-performance wireless noise cancelling hea...,None,None,None,NaN,None,NaN,9,Beats Studio3 Wireless
9,None,64 GB,NaN,None,None,None,None,None,None,None,7.9,None,NaN,10,Apple iPad Mini 5th Gen
10,None,254 GB,NaN,None,None,None,None,None,None,None,7.9,None,NaN,11,Apple iPad Mini 5th Gen
11,None,64 GB,NaN,None,None,None,None,4th,None,419.99,NaN,None,NaN,12,Apple iPad Air
12,None,256 GB,NaN,None,None,None,None,4th,None,519.99,NaN,None,NaN,13,Apple iPad Air